export const DISH_LIST_REQUEST = 'DISH_LIST_REQUEST'
export const DISH_LIST_SUCCESS = 'DISH_LIST_SUCCESS'
export const DISH_LIST_FAIL = 'DISH_LIST_FAIL'

export const DISH_DETAILS_REQUEST = 'DISH_DETAILS_REQUEST'
export const DISH_DETAILS_SUCCESS = 'DISH_DETAILS_SUCCESS'
export const DISH_DETAILS_FAIL = 'DISH_DETAILS_FAIL'

export const DISH_DELETE_REQUEST = 'DISH_DELETE_REQUEST'
export const DISH_DELETE_SUCCESS = 'DISH_DELETE_SUCCESS'
export const DISH_DELETE_FAIL = 'DISH_DELETE_FAIL'