export const DISH_LIST_REQUEST = 'DISH_LIST_REQUEST'
export const DISH_LIST_SUCCESS = 'DISH_LIST_SUCCESS'
export const DISH_LIST_FAIL = 'DISH_LIST_FAIL'

export const DISH_DETAILS_REQUEST = 'DISH_DETAILS_REQUEST'
export const DISH_DETAILS_SUCCESS = 'DISH_DETAILS_SUCCESS'
export const DISH_DETAILS_FAIL = 'DISH_DETAILS_FAIL'

export const DISH_DELETE_REQUEST = 'DISH_DELETE_REQUEST'
export const DISH_DELETE_SUCCESS = 'DISH_DELETE_SUCCESS'
export const DISH_DELETE_FAIL = 'DISH_DELETE_FAIL'

export const DISH_CREATE_REQUEST = 'DISH_CREATE_REQUEST'
export const DISH_CREATE_SUCCESS = 'DISH_CREATE_SUCCESS'
export const DISH_CREATE_FAIL = 'DISH_CREATE_FAIL'
export const DISH_CREATE_RESET = 'DISH_CREATE_RESET'

export const DISH_UPDATE_REQUEST = 'DISH_UPDATE_REQUEST'
export const DISH_UPDATE_SUCCESS = 'DISH_UPDATE_SUCCESS'
export const DISH_UPDATE_FAIL = 'DISH_UPDATE_FAIL'
export const DISH_UPDATE_RESET = 'DISH_UPDATE_RESET'

export const DISH_CREATE_REVIEW_REQUEST = 'DISH_CREATE_REVIEW_REQUEST'
export const DISH_CREATE_REVIEW_SUCCESS = 'DISH_CREATE_REVIEW_SUCCESS'
export const DISH_CREATE_REVIEW_FAIL = 'DISH_CREATE_REVIEW_FAIL'
export const DISH_CREATE_REVIEW_RESET = 'DISH_CREATE_REVIEW_RESET'